export const FETCH_CHARACTERS_LIST_REQUEST = 'FETCH_CHARACTERS_LIST_REQUEST';
export const FETCH_CHARACTERS_LIST_SUCCESS = 'FETCH_CHARACTERS_LIST_SUCCESS';
export const FETCH_CHARACTERS_LIST_FAILED = 'FETCH_CHARACTERS_LIST_FAILED';